---
- name: Install nmap on Ubuntu
  hosts: all
  become: yes  # Run with sudo privileges

  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install nmap package
      apt:
        name: nmap
        state: present
      when: ansible_os_family == "Debian"

    - name: Verify nmap installation (optional)
      command: nmap --version
      register: nmap_version
      changed_when: false  # This task doesn't change the system state
      when: ansible_os_family == "Debian"

    - name: Display nmap version (optional)
      debug:
        msg: "Installed nmap version: {{ nmap_version.stdout }}"
      when: ansible_os_family == "Debian" and nmap_version is defined
