---
- name: Install and configure XRDP on Ubuntu/Debian
  hosts: all
  become: yes  # Run with sudo privileges

    - name: Install XRDP package
      apt:
        name: xrdp
        state: present
      when: ansible_os_family == "Debian"
    
    - name: Ensure XRDP service is started and enabled
      service:
        name: xrdp
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"

    - name: Ensure XRDP-sesman service is started and enabled
      service:
        name: xrdp-sesman
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"

    - name: Restart XRDP service to apply changes
      service:
        name: xrdp
        state: restarted
      when: ansible_os_family == "Debian"
