---
- name: Install nmap on Ubuntu
  hosts: localhost
  become: yes  # Run with sudo privileges

  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install nmap package
      apt:
        name: nmap
        state: present
      when: ansible_os_family == "Debian"
