---
- name: Install nmap on Ubuntu
  hosts: UMTRI
  become: yes  # This enables sudo privileges
  
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      changed_when: false

    - name: Install nmap
      apt:
        name: nmap
        state: present
