---
- name: Write a simple file
  hosts: all
  gather_facts: true
  tasks:
    - name: Write file test.txt to temp directory
      ansible.builtin.lineinfile:
        path: /tmp/test.txt
        line: just a quick simple test 123
        create: true
